# Generated by Django 5.0.8 on 2026-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anprstatus",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "cameraName",
                    models.TextField(blank=True, db_column="CameraName", null=True),
                ),
                ("url", models.TextField(blank=True, db_column="URL", null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "anprstatus",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cameraalerts",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "framePath",
                    models.TextField(blank=True, db_column="FramePath", null=True),
                ),
                (
                    "objectName",
                    models.TextField(blank=True, db_column="ObjectName", null=True),
                ),
                (
                    "objectCount",
                    models.IntegerField(blank=True, db_column="ObjectCount", null=True),
                ),
                (
                    "alertStatus",
                    models.CharField(
                        blank=True, db_column="AlertStatus", max_length=1, null=True
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "cameraalerts",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cameraalertstatuss",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("recording", models.IntegerField(db_column="Recording")),
                ("anpr", models.IntegerField(db_column="ANPR")),
                ("snapshot", models.IntegerField(db_column="Snapshot")),
                ("personDetection", models.IntegerField(db_column="PersonDetection")),
                ("fireDetection", models.IntegerField(db_column="FireDetection")),
                ("animalDetection", models.IntegerField(db_column="AnimalDetection")),
                ("bikeDetection", models.IntegerField(db_column="BikeDetection")),
                ("maskDetection", models.IntegerField(db_column="MaskDetection")),
                ("umbrelaDetection", models.IntegerField(db_column="UmbrelaDetection")),
                (
                    "brifecaseDetection",
                    models.IntegerField(db_column="BrifecaseDetection"),
                ),
                ("garbageDetection", models.IntegerField(db_column="GarbageDetection")),
                ("weaponDetection", models.IntegerField(db_column="WeaponDetection")),
                ("wrongDetection", models.IntegerField(db_column="WrongDetection")),
                ("queueDetection", models.IntegerField(db_column="QueueDetection")),
                ("smokeDetection", models.IntegerField(db_column="SmokeDetection")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "cameraalertstatuss",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CameraDetectionMapping",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("detectionModels", models.TextField(db_column="DetectionModels")),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
            ],
            options={
                "db_table": "camera_detection_mapping",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cameragodownmapping",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
            ],
            options={
                "db_table": "camera_godown",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cameraiplists",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "cameraIP",
                    models.CharField(
                        blank=True, db_column="CameraIP", max_length=255, null=True
                    ),
                ),
                (
                    "objectList",
                    models.TextField(blank=True, db_column="ObjectList", null=True),
                ),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "cameraiplists",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cameras",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=255, null=True
                    ),
                ),
                (
                    "cameraIP",
                    models.CharField(
                        blank=True, db_column="CameraIP", max_length=255, null=True
                    ),
                ),
                ("brand", models.TextField(blank=True, db_column="Brand", null=True)),
                (
                    "manufacture",
                    models.TextField(blank=True, db_column="Manufacture", null=True),
                ),
                (
                    "macAddress",
                    models.TextField(blank=True, db_column="MacAddress", null=True),
                ),
                ("make", models.TextField(blank=True, db_column="Make", null=True)),
                ("port", models.IntegerField(blank=True, db_column="Port", null=True)),
                (
                    "channelId",
                    models.IntegerField(blank=True, db_column="ChannelId", null=True),
                ),
                (
                    "installationDate",
                    models.DateTimeField(
                        blank=True, db_column="InstallationDate", null=True
                    ),
                ),
                (
                    "lastLive",
                    models.DateTimeField(blank=True, db_column="LastLive", null=True),
                ),
                (
                    "rtspurl",
                    models.TextField(blank=True, db_column="RTSPURL", null=True),
                ),
                (
                    "zone",
                    models.IntegerField(blank=True, db_column="ZoneId", null=True),
                ),
                (
                    "location",
                    models.IntegerField(blank=True, db_column="LocationId", null=True),
                ),
                (
                    "isRecording",
                    models.IntegerField(blank=True, db_column="isRecording", null=True),
                ),
                (
                    "isStreaming",
                    models.IntegerField(blank=True, db_column="isStreaming", null=True),
                ),
                (
                    "isAnalytics",
                    models.IntegerField(blank=True, db_column="isAnalytics", null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                (
                    "updateDate",
                    models.DateTimeField(blank=True, db_column="UpdateDate", null=True),
                ),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "cameras",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("name", models.TextField(db_column="name", max_length=255)),
            ],
            options={
                "db_table": "tbl_column_name",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DetectionGroups",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
            ],
            options={
                "db_table": "detection_groups",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("eventId", models.AutoField(primary_key=True, serialize=False)),
                ("eventName", models.CharField(max_length=255, unique=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("conditions", models.JSONField(blank=True, default=list)),
                ("cameras", models.JSONField(blank=True, default=list)),
                ("scheduling", models.JSONField(blank=True, default=dict)),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="userid", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "event",
                "ordering": ["-eventId"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Godown",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("name", models.TextField(db_column="name", max_length=255)),
                (
                    "capacity",
                    models.TextField(blank=True, db_column="capacity", null=True),
                ),
                (
                    "regdate",
                    models.DateTimeField(blank=True, db_column="regDate", null=True),
                ),
            ],
            options={
                "db_table": "godown",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(db_column="Name", max_length=255, unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "groups",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                ("address", models.CharField(db_column="Address", max_length=200)),
                (
                    "landmark",
                    models.CharField(
                        blank=True, db_column="Landmark", max_length=100, null=True
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, db_column="Street", max_length=100, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="City", max_length=100, null=True
                    ),
                ),
                ("state", models.CharField(db_column="State", max_length=100)),
                (
                    "pincode",
                    models.CharField(
                        blank=True, db_column="Pincode", max_length=20, null=True
                    ),
                ),
                ("latitude", models.FloatField(db_column="Latitude")),
                ("longitude", models.FloatField(db_column="Logitude")),
                (
                    "locationType",
                    models.CharField(db_column="LocationType", max_length=100),
                ),
                ("status", models.BooleanField(db_column="Status")),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tbl_location",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Numberplatedetections",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "platePath",
                    models.TextField(blank=True, db_column="PlatePath", null=True),
                ),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "numberplatedetections",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nvr",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=255, null=True
                    ),
                ),
                ("nvrip", models.TextField(blank=True, db_column="NVRIP", null=True)),
                ("port", models.IntegerField(db_column="Port")),
                (
                    "username",
                    models.TextField(blank=True, db_column="Username", null=True),
                ),
                (
                    "password",
                    models.TextField(blank=True, db_column="Password", null=True),
                ),
                (
                    "nvrtype",
                    models.TextField(blank=True, db_column="NVRType", null=True),
                ),
                ("model", models.TextField(blank=True, db_column="Model", null=True)),
                (
                    "location",
                    models.TextField(blank=True, db_column="Location", null=True),
                ),
                ("make", models.TextField(blank=True, db_column="Make", null=True)),
                ("zone", models.TextField(blank=True, db_column="Zone", null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, db_column="IMG", null=True, upload_to="data/images"
                    ),
                ),
                (
                    "responsible_Person",
                    models.TextField(
                        blank=True, db_column="Responsible_Person", null=True
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "nvr",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Readedvehiclenoplates",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "framePath",
                    models.TextField(blank=True, db_column="FramePath", null=True),
                ),
                (
                    "platePath",
                    models.TextField(blank=True, db_column="PlatePath", null=True),
                ),
                ("text", models.TextField(db_column="Text")),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "readedvehiclenoplates",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_column="Name",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
            ],
            options={
                "db_table": "roles",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "firstName",
                    models.TextField(blank=True, db_column="FirstName", null=True),
                ),
                (
                    "lastName",
                    models.TextField(blank=True, db_column="LastName", null=True),
                ),
                (
                    "mobileNo",
                    models.CharField(
                        blank=True,
                        db_column="MobileNo",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "emailId",
                    models.CharField(
                        blank=True,
                        db_column="EmailId",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_column="Username",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.TextField(blank=True, db_column="Password", null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_column="Image",
                        null=True,
                        upload_to="data/images",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicledetections",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "framePath",
                    models.TextField(blank=True, db_column="FramePath", null=True),
                ),
                (
                    "vehicleType",
                    models.TextField(blank=True, db_column="VehicleType", null=True),
                ),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "vehicledetections",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Videoanalytics",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "cameraIP",
                    models.TextField(blank=True, db_column="CameraIP", null=True),
                ),
                (
                    "rtspUrl",
                    models.TextField(blank=True, db_column="RTSPUrl", null=True),
                ),
                (
                    "objectList",
                    models.TextField(blank=True, db_column="ObjectList", null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "True"), (0, "False")],
                        db_column="Status",
                        default=0,
                    ),
                ),
                ("regDate", models.DateTimeField(auto_now=True, db_column="RegDate")),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "videoanalytics",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                ("status", models.BooleanField(db_column="Status", default=True)),
                (
                    "regDate",
                    models.DateTimeField(auto_now_add=True, db_column="RegDate"),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, db_column="UserId", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tbl_zone",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
    ]
