streams:
  cam_18:
  - rtsp://admin:admin%40123@14.195.152.243:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  cam_19:
  - rtsp://admin:admin%40123@14.195.152.243:554/cam/realmonitor?channel=4&subtype=0&unicast=true&proto=Onvif
  cam_20:
  - rtsp://admin:admin%40123@14.195.152.243:554/cam/realmonitor?channel=5&subtype=0&unicast=true&proto=Onvif
  cam_21:
  - rtsp://admin:admin%40123@14.195.152.243:554/cam/realmonitor?channel=3&subtype=0&unicast=true&proto=Onvif
  cam_22:
  - rtsp://admin:admin%40123@14.195.152.243:554/cam/realmonitor?channel=2&subtype=0&unicast=true&proto=Onvif
  cam_23:
  - rtsp://admin:admin@123@14.195.152.243:554/cam/realmonitor?channel=4&subtype=0&unicast=true&proto=Onvif
  cam_24:
  - rtsp://admin:admin123@192.168.0.63:554/stream1
  cam_25:
  - rtsp://admin:admin123@192.168.0.63:554/stream1
  cam_26:
  - rtsp://admin:admin123@192.168.0.63:554/stream1
  cam_27:
  - rtsp://admin:admin123@192.168.0.63:554/stream1
  cam_28:
  - ffmpeg:rtsp://admin:admin123@192.168.0.63:554/stream1#video=h264
  cam_29:
  - ffmpeg:rtsp://admin:admin123@192.168.0.63:554/stream1#video=h264
  cam_30:
  - rtsp://admin:admin123@192.168.0.63:554/stream1
  cam_31:
  - ffmpeg:rtsp://admin:admin123@192.168.0.63:554/stream1#video=h264
  demo:
  - rtsp://admin:admin123@192.168.0.63:554/stream1
  demo10:
  - rtsp://admin:admin123@192.168.0.63:554/stream1
  demo2:
  - ffmpeg:rtsp://admin:admin123@192.168.0.63:554/stream1#video=h264
  demo5:
  - ffmpeg:rtsp://admin:admin123@192.168.0.63:554/stream1#video=h264
